TodayPage 추가
GooseMoment/Peak pull request #226
Opened 2024-08-14 18:22 UTC by minyoy

**TodayPage**
---
![image](https://github.com/user-attachments/assets/7e021029-c1fd-4ce9-a4b7-4bc476a865bb)
![image](https://github.com/user-attachments/assets/41e27b5e-230b-4b99-9836-48f1df6fb182)

- 지난 기한, 지난 할당 버튼을 통해 `지난 기한 작업 및 할당 작업들`을 확인해볼 수 있습니다.
- `더보기 옆 숲자`는 `지난 기한/할당 작업의 수`입니다.
- `지난 기한 창`에서 ArrowDown을 클릭 시 `기한이 오늘`로 설정되며, ArrowRight을 클릭 시 `기한이 내일`로 설정됩니다.
- `지난 할당 창`에서 ArrowDown을 클릭 시 `할당이 오늘`로 설정되며, ArrowRight을 클릭 시 `할당이 내일`로 설정됩니다.
- `TaskCircle의 색상`은 `프로젝트의 색상`을 따릅니다.
- 박스 아래 오늘 할일들은 `assigned_at이 우선 정렬`되게 하였습니다.
- `TaskFrame`의 `max_width props`을 추가하였습니다. 기본값은 **60em**입니다.
- 번역 및 테마 색상 모두 적용하였습니다.

**아직 추가되지 않은 것들**
---
- 달력을 추가해 각 날짜에 맞는 기한과 할당을 보여줄 계획입니다.
- ArrowDown과 ArrowRight 아이콘에 hover 시 툴팁으로 기한을 설정할 수 있다는 것을 알려줄 계획입니다.

2024-09-14 14:12 UTC, minyoy commented
![image](https://github.com/user-attachments/assets/80a4f5d1-e372-45a5-a9a6-badc13b7f3ab)
놓친 작업을 볼 수 있는 화면을 접는 기능을 추가했습니다!

2024-09-16 02:25 UTC, JedBeom requested changes
#251 PR 리뷰하시고 머지하시면 그 때 Approve 하도록 하겠습니다.

2024-09-20 05:39 UTC, JedBeom approved these changes

2024-09-20 05:40 UTC, JedBeom commented
LGTM

2024-09-20 05:40 UTC, merged