Task 드래그 앤 드롭 추가
GooseMoment/Peak pull request #252
Opened 2024-09-20 08:48 UTC by minyoy

**Task 드래그 앤 드롭 추가**
---
_브랜치 이름을 수정하여 다시 PR 올렸습니다._

![image](https://github.com/user-attachments/assets/b8f98096-507f-475f-884c-21e2901975be)
마우스 호버 시 드래그 앤 드롭 버튼이 나타납니다.

![image](https://github.com/user-attachments/assets/f09f6d40-4df0-4ea3-8128-840791c96476)
드래그 앤 드롭 버튼을 사용해 드래그할 시 이동할 수 있는 부분에 가이드라인이 나오며, 드롭 시 `Task`의 order를 변경할 수 있습니다.
* 가이드라인 색상은 추후에 #216 PR이 merge되면 프로젝트 색상으로 변경할 예정입니다.

+ 새로운 `Task`를 추가 시, 맨 아래에 위치합니다.
+ 드래그 앤 드롭 버튼이 추가되면서 `Task`의 margin과 스켈레톤의 margin을 변경하였습니다.

---

본 PR에서 적용되지 않아 추후에 적용될 것들
- 정렬 기능을 사용해 정렬하면 지금은 정렬이 유지되지 않지만, 추후 PR로 유지되게 변경할 것입니다.
- 서랍과 프로젝트 드롭다운도 추가할 예정입니다.

* 드롭다운이 가끔 잘못 적용되는 경우가 있던데 일관된 패턴을 찾지 못해 오류를 수정하지 못했습니다 ㅠㅠ 혹시 일관된 패턴을 찾으신다면 이슈 남겨주세요!

2024-09-26 15:24 UTC, JedBeom requested changes
모두가 염원하던 그 기능, 드래그해서 작업 목록 수정하기!
몇 가지 수정사항만 남깁니다. 감사합니다!

2024-09-26 15:24 UTC, JedBeom commented on backend/tasks/models.py
> +    order=models.IntegerField(default=0)
할당 연산자 `=`의 양 쪽에 공백을 넣어주세요.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
> +            onDrop({ location, source }) {
`onDrop` 함수를 `Drawer`의 다른 곳에서 정의하면 들여쓰기 수준을 줄일 수 있을 것 같습니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
> +                if (targetData !== undefined && draggedOrder !== undefined) {
```js
if (targetData === undefined || draggedOrder === undefined) {
    return
}
```
예외상황을 먼저 제거하고, 해피 패스만 유지하는 게 좋을 것 같습니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
> +                    if (typeof targetOrder === "number" && draggedOrder !== targetOrder) {
```js
if (typeof targetOrder !== "number" || draggedOrder === targetOrder) {
    return
}
```

예외상황을 먼저 제거하고, 해피 패스만 유지하면 들여쓰기 수준을 줄일 수 있습니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
> +                            <DragAndDownBox key={task.id} task={task}>
`DragAndDownBox`에도 `color`를 넘길 수 있으면 좋을 것 같습니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
해당 파일에 prettier 실행 부탁드립니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
> +            }
들여쓰기 수준을 낮추기 위해, 이 함수들을 `DragAndDownBox` 바로 안에서 정의하는 것을 추천합니다.

2024-09-26 15:24 UTC, JedBeom commented on frontend/src/components/project/dragAndDown/DragAndDownBox.jsx
https://github.com/user-attachments/assets/63b4b5d2-e368-44dc-a2de-301b802a3744

점선이 빠르게 나타나지 않는 경우가 있습니다.

2024-09-27 07:58 UTC, minyoy commented
코멘트 감사합니다! 모두 수정하였습니다 :)

2024-09-27 22:20 UTC, JedBeom approved these changes
LGTM 😍

2024-09-27 22:20 UTC, merged