Search Page
GooseMoment/Peak pull request #253
Opened 2024-09-21 14:15 UTC by andless2004

# Search
> - 부족한 부분이 여전히 많지만 Search 페이지가 추가되었습니다.
> - 구조를 여러 번 갈아엎고 추후 도입할 필터 그룹에 대한 생각이 자주 바뀌어 state와 searchParams를 병용하게 되었습니다. 불필요한 자원 낭비, 복잡한 구조 등의 문제가 발생한다면 정정하겠습니다.
> ![image](https://github.com/user-attachments/assets/62dfd88b-895c-4f21-8775-e8e2472bef58)
> ## FilterButton
> ![image](https://github.com/user-attachments/assets/1f234309-5dc2-4435-9714-6400640ff62c)
> - 버튼을 클릭 후 입력하면 활성화됩니다.
> - 입력 문자열 길이에 따라 버튼 길이가 달라지는 것을 구현하기 위해 span을 복제하는 방법을 사용했습니다. 좋은 방법 있다면 훈수 부탁드립니다.
> ## FilterResults
> ![image](https://github.com/user-attachments/assets/6f3605f2-756a-4a02-b248-9ed346aa271a)
> - 아직 우선순위와 결과 화면 표시에 대한 생각이 정리되지 않아 나열하여 보여줍니다.
> - 또한, 유사도 계산을 위해 여러 방법을 사용했는데 생각한 결과가 나오지 않아 추후 도입하겠습니다.

# Others
> - Search의 FilterButton이 CommonCaledar를 모달로 띄우고 선택 이후 닫히는 동작을 위해 isModal, handleCloase 파라미터를 추가했습니다. 
> - Social Exlpore 페이지의 SearchBar 도 동일한 디자인으로 변경하는 것에 대한 의견이 궁금합니다!
> - 여러모로 많은 지연이 있었음에도 좋은 결과물을 가져오지 못해 사과의 말씀 드립니다..

2024-09-22 15:47 UTC, JedBeom commented
안녕하세요, 코드 리뷰 하기 전에 몇 가지 사항 남깁니다.

1. 날짜를 캘린더에서 선택하면 Invalid Date라고 나옵니다.

<img width="669" alt="Screenshot 2024-09-22 at 11 45 44" src="https://github.com/user-attachments/assets/c5e06e2e-62ab-4f18-ba6c-65448ddc272f">

2. 필터값이 없거나(빈 문자열), 잘못된 값이면 아예 그 값은 없는셈 쳐야할 것 같습니다.
<img width="623" alt="Screenshot 2024-09-22 at 11 46 14" src="https://github.com/user-attachments/assets/4525fd58-de99-4044-a27d-f2b0b2310d15">

3. 이번에도 test 버튼이 숨어있습니다.
<img width="177" alt="Screenshot 2024-09-22 at 11 46 46" src="https://github.com/user-attachments/assets/7836022b-e92f-4b15-8805-6c20cc305e22">

4. completed_at을 날짜로도, 여부로도 찾을 수 있으면 좋을 것 같습니다. (완료되었는지 여부로 검색)

해당 사안 고려해보시면 좋을 것 같습니다! 감사합니다.

2024-09-22 16:46 UTC, andless2004 commented
1, 2 는 확인 후 수정하겠습니다! param 값을 가져오는 것으로 바꾸며 제가 전처리를 빠뜨린 것 같습니다. 제가 확인 후 원인이 그게 아니라면 나중에 번거로우시겠지만 입력값 확인 부탁드려도 될까요?

3. SocialExplore의 search와 마찬가지로 제대로 사용을 못했습니다.. 함께 수정하겠습니다!

4. 좋은 의견 감사합니다! 그와 함께 "오늘", "이번 주", "이번 달" 등 키워드형 값도 넣을 것을 고려하고 있습니다. 다만 react-calendar를 원하는 대로 사용하지 못하고 있어 해당 기능들을 넣는 것이 미뤄진 점 양해 부탁드립니다. CommonCalendar를 빠른 시일 내로 수정 후 개선하겠습니다.

4+. FilterGroup의 값들을 localStorage나 Persistent cookies(쿠키는 크게 생각하고 있지 않음)에 저장하는 것을 고려하고 있습니다. 이에 대한 의견도 남겨주시면 감사하겠습니다. 
또한, 필터 디자인에 관해서 좋은 의견 있으시면 언제든지 말씀해주시면 감사하겠습니다! @JedBeom @minyoy

2024-09-24 19:47 UTC, JedBeom requested changes
코드 리뷰 전에, 앞서 말씀드린 사항의 수정을 기다리고 있겠습니다!

2024-09-26 15:28 UTC, JedBeom commented
의견 하나 남깁니다.
SearchPage의 간소화를 위해, OR조건은 고려하지 않고 전부 AND조건으로 처리하는 게 어떨까요?

2024-10-05 05:30 UTC, JedBeom requested changes
1차 수정 감사합니다! 이번에는 코드에 관한 변경사항 및 제안사항을 남깁니다.
항상 수고해주셔서 감사합니다!

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +from rest_framework.decorators import api_view
These imports are not accessed.

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +from django.views.decorators.cache import cache_page
These imports are not accessed.

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +from tasks.serializers import TaskSerializer
"TaskSerializer" is not accessed

2024-10-05 05:30 UTC, JedBeom commented on frontend/public/locales/ko/translation.json
> +            "search_terms" : "검색어",
혹시 사용되지 않는 번역인가요?

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +    value = value.split('to')
ISO 8601에는 시간의 범위를 나타낼 때 `/`를 사용합니다. [위키피디아](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) (ISO 공식 문서를 링크하고 싶었는데, 돈 주고 문서를 팔고 있네요 😩)

예: 
```
2024-10-08T04:00:00.000Z/2024-10-14T03:59:59.999Z
```

`to` 대신에 `/`로 시작과 끝 날짜를 구분하는 것을 고려해보시면 좋을 것 같습니다!

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +    pass
`len(value) != 2`일 때 먼저 리턴하는 건 어떨까요?

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/api/search.api.js
> +    const searchparam = new URLSearchParams()
camelCase를 사용해주세요!

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/api/search.api.js
> +    const res = await client.get(`search/?${searchparam}&cursor=${cursor}`)
URL에 스트링 형태로 삽입하는 것 대신, `searchparam`을 값 형태로 전달하는 것이 더 좋습니다.

```js
searchparam.set("cursor", cursor)
const res = await client.get(`search/`, { params: searchparam })
```

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/CalendarModal.jsx
<img width="355" alt="Screenshot 2024-10-05 at 01 18 23" src="https://github.com/user-attachments/assets/5f3cafd0-bc32-4f9a-b1ff-29529c0786bc">

`CalendarModal`이 `TaskFrame`의 `TaskCircle`과 다른 아이콘들에 가려집니다.

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/CalendarModal.jsx
> +    const initial_date = new Date()
camelCase를 사용해주세요.

2024-10-05 05:30 UTC, JedBeom commented on backend/search/views.py
> +        return 0
<img width="506" alt="Screenshot 2024-10-05 at 01 21 09" src="https://github.com/user-attachments/assets/e12e5d48-21b6-4573-a9dc-ff8ec35557e2">

이 부분에서 500 에러가 발생합니다.

(privacyFilter로 `"ㅁㄴㅇㄹ"`을 입력함)

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/FilterButton.jsx
> +    }
모바일은 `:hover`에 대응하기 어렵습니다. 모바일 환경에서의 상황을 고려해주세요.

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/FilterButton.jsx
> +        <>
Fragment가 하나의 요소만 감싸고 있다면, Fragment를 삭제하는 것도 고려해도 좋을 것 같습니다.

2024-10-05 05:30 UTC, JedBeom commented on backend/search/serializers.py
> +        fields = TaskSerializer.Meta.fields + ['color']
`TaskSerializer`에 `project_color`가 포함되어 있습니다. `SearchResultsSerializer`에 `color` 이외의 속성을 추가할 계획이 없다면 `TaskSerializer`를 사용해도 좋을 것 같습니다!

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/FilterButton.jsx
> +                    ? filter.name + " : "
`:`의 왼쪽 공백을 지우는 게 어떨까요? 쌍점은 앞엔 붙여서, 뒤는 한 칸 띄어서 써야합니다.

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/FilterInput.jsx
> +            <>
Fragment 안에 하나 밖에 없다면 Fragment를 지우는 것을 고려해보는 게 좋을 것 같습니다.

2024-10-05 05:30 UTC, JedBeom commented on frontend/src/components/search/SearchResults.jsx
> +                        <TaskFrame task={task} color={task.color} />
`getProjectColor`를 적용해야 합니다.

2024-10-05 05:57 UTC, andless2004 commented on frontend/public/locales/ko/translation.json
> +            "search_terms" : "검색어",
search_terms를 말씀하시는 거면 접근성 대체 텍스트로 나중에 넣고자 하는 생각이 있습니다!

2024-10-15 01:20 UTC, andless2004 commented on backend/search/views.py
> +    value = value.split('to')
좋은 의견 감사합니다!

2024-10-15 01:22 UTC, andless2004 commented on backend/search/views.py
> +    pass
이건 나중에 날짜 선택을 수정하려고 그렇습니다! 단일 날짜, 키워드 등의 기능을 추가할 예정입니다.

2024-10-15 01:23 UTC, andless2004 commented on backend/search/views.py
> +        return 0
Project와 Drawer 옵션에서 목록 생성과 및 자동 완성 기능을 넣으며 Privacy는 다시 추가하겠습니다.

2024-10-15 01:24 UTC, andless2004 commented on backend/search/serializers.py
> +        fields = TaskSerializer.Meta.fields + ['color']
세상이 너무 빠르게 변화하네요ㅠ 감사합니다!!!

2024-10-15 01:25 UTC, andless2004 commented on frontend/src/components/search/FilterButton.jsx
> +                    ? filter.name + " : "
좋은 지적입니다! 버튼이 너무 빽빽한 느낌이 들어 공백을 넣었는데 다시 생각해보니 그게 좋을 것 같습니다.

2024-10-15 04:04 UTC, JedBeom requested changes
수정 감사드립니다. 몇 가지 더 코멘트 남깁니다.
읽어보시고 확실하지 않은 부분 있으면 답글 달아주시기 바랍니다.
감사합니다!

2024-10-15 04:04 UTC, JedBeom commented on frontend/public/locales/en/translation.json
> +        "no_result" : "I can't find anything 🤔"
제안: `"Your search did not match any tasks."

2024-10-15 12:27 UTC, andless2004 commented on frontend/public/locales/en/translation.json
> +        "no_result" : "I can't find anything 🤔"
오 좋아욥

2024-10-15 12:34 UTC, andless2004 commented on frontend/src/components/search/CalendarModal.jsx
> +    )
아? 그러게요..? 왜 그랬지..? 감사합니다!

2024-10-15 15:26 UTC, andless2004 commented on frontend/src/components/search/SearchResults.jsx
> +                            <DrawerBox $color={color}>
좋은 의견 감사합니다!
이전 페이지로 돌아올 때의 동작은 우선 고민해봐야 할 것 같습니다. filter 값들을 지속적으로 localstorage에 업데이트하는 것은 그닥 좋은 생각 같지 않아서 searchParams를 다시 사용하던가 해야할 것 같습니다.. 다른 의견 있으시면 편하게 부탁드립니다!

2024-10-15 15:35 UTC, JedBeom commented on frontend/src/components/search/CalendarModal.jsx
> +    )
어떤 이슈인가요?

2024-10-15 15:36 UTC, JedBeom commented on frontend/src/components/search/SearchResults.jsx
> +                            <DrawerBox $color={color}>
localStorage에 저장하는 것도 괜찮지 않나요? 사용자가 입력하는 것을 사용자 브라우저에 저장하는 것이고, 사용자가 컴퓨터의 속도로 값을 입력하는 게 아니니 값 변경 주기도 심하지 않을 것 같습니다.

2024-10-28 05:58 UTC, andless2004 commented on frontend/src/components/search/SearchResults.jsx
> +                            <DrawerBox $color={color}>
오호 그 정도 주기는 괜찮을까요? 고의적인? 좀 극단적인 경우를 상정하긴 했는데 생각해보니 괜찮을 거 같네요..
LocalStorage는 다른 PR로 추가하겠습니다!

2024-10-28 17:05 UTC, JedBeom requested changes
변경에 감사드립니다. 스타일 관련 문제 딱 한 가지만 더 확인해주세요!

2024-10-28 17:05 UTC, JedBeom commented on frontend/src/components/search/SearchBar.jsx
<img width="585" alt="Screenshot 2024-10-28 at 13 03 19" src="https://github.com/user-attachments/assets/7054eb7b-e484-4989-ba6f-33b4e250ba7b">

너비가 550px 부근일 때 여전히 검색 아이콘이 가려져 보이는 문제가 있습니다. 이는 `input`의 너비가 flex에 맞게 줄어들지 않아서 생기는 문제입니다. `SearchInput`에 `min-width: 0`을 추가하면 해결할 수 있습니다.

2024-10-30 06:11 UTC, andless2004 commented on frontend/src/components/search/CalendarModal.jsx
> +    )
Month view에서 prop type을 지정해 놓아 null을 허용하지 않기 때문인 것 같습니다! 선택 버튼을 추가로 두는 등의 수정을 통해 해당 불편함을 해소할 수 있을 것 같습니다..
이 문제는 좀 더 고민해 보겠습니다!

2024-10-30 06:16 UTC, andless2004 commented on frontend/src/components/search/SearchBar.jsx
![image](https://github.com/user-attachments/assets/0df79815-6602-4749-a705-08bfaef416c9)
혹시 지금도 그런가요...? 브라우저 차이일까요...?

2024-10-30 16:36 UTC, JedBeom commented on frontend/src/components/search/SearchBar.jsx
크롬에서만 올바르게 보이고, 사파리와 파이어폭스에서는 이상하게 보이는 것을 확인했습니다.

<img width="686" alt="Screenshot 2024-10-30 at 12 35 19" src="https://github.com/user-attachments/assets/1b05b61c-1b49-45de-a64f-d0c700da2542">

2024-10-31 03:29 UTC, andless2004 commented on frontend/src/components/search/SearchBar.jsx
아하 감사합니다!

2024-10-31 04:24 UTC, JedBeom approved these changes
한 달 넘었던 대장정을 마무리짓습니다. 수고하셨습니다!

2024-10-31 04:24 UTC, merged