TodayPage 코드 수정 + #255 추가
GooseMoment/Peak pull request #259
Opened 2024-09-26 07:55 UTC by minyoy

- `TodayPage`와 관련된 `backend`나 `api`가, `tasks` 폴더에 들어있던 것들을 `today` 폴더로 옮겼습니다.
- backend에서 today를 불러올 때, `today`를 계산하는 방식을 수정하였습니다.
- issue #255를 추가했습니다.

+현재 `TodayPage`에서 오늘 할 일은 **할당 날짜**가 오늘인 것만 보여집니다. (기한만 오늘인 것은 보여지지 않습니다.)
추후에 디자인을 수정한 후 기한이 오늘인 작업들을 보여줄 예정입니다.

2024-09-26 14:56 UTC, JedBeom requested changes
수고하셨습니다! 몇 가지 제안과 몇 가지 수정사항을 남깁니다. 확인해주시면 감사하겠습니다!

2024-09-26 14:56 UTC, JedBeom commented on backend/today/views.py
> +            Q(completed_at__isnull=True)
OR 조건이 필요하지 않으므로, 전부 Q()를 벗길 수 있습니다.

2024-09-26 14:56 UTC, JedBeom commented on backend/today/views.py
> +class TodayAssignmentTaskList(mixins.ListModelMixin, generics.GenericAPIView):
제안: TaskTodayAssignedList는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on backend/today/views.py
> +            Q(completed_at__isnull=True)
OR조건이 없으므로, 전부 Q를 벗길 수 있습니다.

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/api/today.api.js
> +export const getTodayAssignmentTasks = async (day, page) => {
제안: getTasksAssignedToday는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/api/today.api.js
> +export const getTodayDueTasks = async (day, page) => {
제안: getTasksDueToday는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/api/today.api.js
> +export const getOverdueTasks = async (filter_field, page) => {
제안: getTasksOverdue는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on backend/today/views.py
> +class TodayDueTaskList(mixins.ListModelMixin, generics.GenericAPIView):
제안: TaskTodayDueList는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on backend/today/views.py
> +class OverdueTaskList(mixins.ListModelMixin, generics.GenericAPIView):
제안: TaskOverdueList는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/components/tasks/Task.jsx
> +                queryKey: ["today", "assignment"],
제안: ["today", "assigned"] 는 어떨까요?

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/pages/TodayPage.jsx
<img width="1075" alt="Screenshot 2024-09-26 at 10 51 47" src="https://github.com/user-attachments/assets/9e38b8d1-8886-43a3-aa9f-4b25340fc0b6">

Overdue인 작업 목록에서 화살표를 누르면 기한을 바꾸는 게 아닌 오늘로 **할당**이거나 내일로 **할당**되는 건 어떤가요?

2024-09-26 14:56 UTC, JedBeom commented on frontend/src/pages/TodayPage.jsx
> +`
글씨가 일반 크기에 일반 굵기에 회색이면 더 좋을 것 같습니다!

2024-09-26 15:33 UTC, JedBeom commented
추가로, `backend/django_peak/settings.py`의 `INSTALLED_APPS`에서 `"today"`를 주석 해제 처리 부탁드립니다.

2024-09-27 06:05 UTC, minyoy commented on frontend/src/pages/TodayPage.jsx
**오늘 기한**을 따로 보여줄 생각이고, 오늘 기한 목록에서 화살표를 누르면 오늘/내일 할당이 변경될 예정인데 이것도 할당을 변경하는 것이 좋을까요..???

2024-09-27 06:11 UTC, minyoy commented
제안과 수정사항 감사합니다! 코멘트 단 한가지를 제외하고는 모두 수정하였습니다!

2024-09-27 07:50 UTC, JedBeom commented on frontend/src/pages/TodayPage.jsx
네! 오늘 페이지에서 보여주는 주 내용은 오늘로 할당된 작업이기 때문에, 오늘 페이지에 있는 모든 아래 화살표는 오늘로 할당이 되어야합니다.

2024-09-27 08:22 UTC, minyoy commented
+
Overdue인 작업 목록에서 화살표를 누르면 할당 날짜가 오늘/내일로 바뀌도록 수정하였습니다.
Overdue인 작업 목록에서 오늘 할당인 작업들은 보이지 않습니다.

2024-09-27 22:31 UTC, JedBeom requested changes
코드 수정 감사합니다! 이제 텍스트 관련해서 몇 가지 요청사항 남깁니다. 항상 감사합니다 ☺️

2024-09-27 22:31 UTC, JedBeom commented on frontend/public/locales/en/translation.json
> +        "due_change_tomorrow_success": "Changed Missed to tomorrow.",
제안: `"Assigned the task to today."`, `"Assigned the task to tomorrow."`

2024-09-27 22:31 UTC, JedBeom commented on frontend/public/locales/ko/translation.json
> +        "due_change_tomorrow_success": "지난 할당을 내일로 변경했습니다.",
제안: `"작업을 오늘로 할당했습니다."`, `"작업을 내일로 할당했습니다."`

2024-09-27 22:31 UTC, JedBeom commented on backend/today/views.py
> +class TaskTodayAssignmentList(mixins.ListModelMixin, generics.GenericAPIView):
api 엔드포인트와 프론트엔드의 api 콜백함수에 맞추어 `Assigned`로 이름을 통일하는 게 좋을 것 같습니다.

2024-09-27 22:31 UTC, JedBeom commented on backend/today/views.py
> +        day = self.request.GET.get('day')
TaskOverdue는 `day` 인자 필요없이 **오늘** 기준으로만 계산하면 되지 않나요?

2024-09-27 22:32 UTC, JedBeom commented
추가로, `main` 브랜치와의 머지 컨플릭트로 해결 부탁드립니다.

2024-09-29 17:58 UTC, minyoy commented
모두 수정했습니다~

2024-09-30 00:45 UTC, JedBeom approved these changes
LGTM 🤗

2024-09-30 00:45 UTC, merged