ProjectListPage 생성버튼 추가+공개범위에 따른 아이콘 표시+SocialPage에서 Task 색상변경+Drawer 더보기 버튼 loading 옵션 추가
GooseMoment/Peak pull request #263
Opened 2024-09-29 09:13 UTC by minyoy

**- ProjectListPage의 Title 옆에 생성버튼을 추가했습니다.**

![image](https://github.com/user-attachments/assets/a6622525-3274-4688-8da0-7b690e92c51c)

**- 공개 범위에 따라 아이콘을 표시하도록 하였습니다.**

![image](https://github.com/user-attachments/assets/9006b5ad-ac6f-456f-b352-46e4a94c604e)
전체공개 - 아이콘X
![image](https://github.com/user-attachments/assets/0a24a58f-23e2-4d5e-8a28-721d1f134db0)
팔로워공개
![image](https://github.com/user-attachments/assets/98177f80-4b58-47ff-926e-01180232735d)
비공개

**- SocialPage에서 완수된 작업이 회색글씨로 보였지만, 이제는 흰색으로 표시됩니다.
+SocialPage에서는 할당날짜, 기한이 각 색깔로 표시되지 않고 흰색으로 표시됩니다.**

![image](https://github.com/user-attachments/assets/7a3e645c-83d1-4d97-8c94-2b1f717f77a9)

**- Drawer의 더보기 버튼에 loading과 disabled 옵션을 추가했습니다.**

2024-09-30 00:59 UTC, JedBeom requested changes
여러 수정 사항 감사합니다. 작동하지 않는 것에 대해서, 그리고 개선하면 좋을 것들에 대해서 리뷰 남겼습니다. 확인 부탁드립니다!

2024-09-30 00:59 UTC, JedBeom commented on frontend/src/pages/ProjectPage.jsx
> +                    </PrivacyBox>}
`Drawer`에서도 공통된 코드가 사용됩니다. `privacy`와 `color`를 받는 공용 컴포넌트로 분리하면 좋을 것 같습니다.

2024-09-30 00:59 UTC, JedBeom commented on frontend/src/components/drawers/Drawer.jsx
> +                        loading={isPending}
`useInfinityQuery`에서 다음 페이지를 불러오는 상태를 확인하고 싶을 때는 `isPending` 대신 `isFetchingNextPage`를 사용해야 합니다.

2024-09-30 00:59 UTC, JedBeom commented on frontend/src/pages/ProjectPage.jsx
> +        stroke: ${props=>props.$color};
Privacy 아이콘이 좀 더 두꺼워도 괜찮을 것 같습니다.

2024-09-30 00:59 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskCalculation.jsx
> +        if (diff.years < 0 || diff.months < 0 || diff.days < -1) {
하나의 if문으로 통합하는 건 어떨까요?

2024-09-30 00:59 UTC, JedBeom commented on frontend/src/components/tasks/TaskFrame.jsx
> +    const updatedCompletedAt = isSocial ? null : task.completed_at
`completed_at` 값이 실제로 업데이트되는 건 아니기 때문에, 그냥 `completedAt`이라고 이름 붙이는 게 좋을 것 같습니다.

2024-09-30 06:00 UTC, minyoy commented
리뷰 감사합니다! 모두 수정하였습니다 👍

2024-09-30 16:28 UTC, JedBeom requested changes
수정 감사합니다! 두 가지 관례적인 사항에 대해서 코멘트 남겼습니다. 두 가지만 더 수정 부탁드립니다!

2024-09-30 16:28 UTC, JedBeom commented on frontend/src/components/project/common/PrivacyIcon.jsx
> +        return
리액트 컴포넌트에서 아무 것도 반환하고 싶지 않을 때는 `undefined` 대신 `null`을 반환하는 것을 추천합니다.

FYI: React 17까지는 `undefined`을 반환하면 런타임 에러가 발생했지만, React 18(Peak이 사용하는 버전)부터는 `undefined`을 반환해도 에러는 발생하지 않습니다. ([관련 PR](https://github.com/reactwg/react-18/discussions/75)) 하지만 여전히 `null`을 반환하는 것이 격려됩니다.

2024-09-30 16:28 UTC, JedBeom commented on frontend/src/pages/ProjectPage.jsx
> +                    <PrivacyIcon privacy={project.privacy} color={getProjectColor(theme.type, project.color)} isProject/>
이 파일에 Prettier를 실행 부탁드립니다.

2024-10-02 01:56 UTC, JedBeom commented
머지 컨플릭트도 해결 부탁드립니다. Prettier 먼저 실행 후 머지 시도하시면 깔끔하게 머지될 것 같습니다.

2024-10-02 07:39 UTC, minyoy commented
코멘트 감사합니다! 머지 컨플릭트도 수정 완료했습니다~

2024-10-02 17:40 UTC, JedBeom approved these changes
LGTM

2024-10-02 17:40 UTC, merged