Task의 Due 수정 + #202 + #235
GooseMoment/Peak pull request #268
Opened 2024-10-03 09:15 UTC by minyoy

### PR #264 에 따라 `Task`의 Due를 수정
---
Due의 구성을 `due_tz`, `due_date`, `due_time` 에서 `due_type`, `due_date`, `due_datetime`으로 바꾸었습니다.
(*due_type : null || "due_date" || "due_datetime" 값이 들어갑니다.)

기한이 없을 경우에는 `due_type`, `due_date`, `due_datetime` 모두에 `null` 값이 들어갑니다.
기한이 날짜만 있을 경우에는 `due_type` = "due_date", `due_date`에 날짜 값이, `due_datetime`에 `null` 값이 들어갑니다.
기한이 날짜+시간인 경우는 `due_type` = "due_datetime", `due_date`에 `null` 값이, `due_datetime`에 datetime 값이 들어갑니다.

Due의 구조가 바뀜에 따라, `Assigned`, `Due`, `TimeDetail`, `SimpleDue`, `TodayPage`, `taskCalculation`, `taskDate` 등의 파일들을 수정하였습니다.

+ #202 #235 이슈 두 개도 해결하였습니다.

*기존 Task에 설정되었던 due에는 due_type이 지정되어있지않아 기한 재설정 시 오류가 날 수 있습니다 ㅠㅠ 불편하시겠지만 admin에서 기존 due를 없앤 후에 기한을 재설정해주시길 바랍니다..!

2024-10-03 09:35 UTC, minyoy commented
![image](https://github.com/user-attachments/assets/c633faf7-e1a0-4bd6-adae-0725ed79a8c5)
시간 제거 버튼을 추가하였습니다!

- due_datetime이 설정되어있고, 날짜를 재설정할 때 -> due_time은 유지되고 due_date만 재설정됨
- due_datetime이 설정되어있고, 시간을 제거하면 -> due_date만 유지되고 due_time은 없어짐(due_type도 due_date로 수정)

2024-10-04 05:29 UTC, JedBeom requested changes
`due_datetime`의 진화에 감격했습니다.
하지만 여전히 시간대 문제는 우리를 괴롭히는 듯 합니다.
시간대 문제를 타파할 수 있는 몇 가지 리뷰 코멘트를 달았습니다.
확인해 주시고 명확하지 않은 부분 있으면 알려주세요!

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskDate.jsx
`due_date`와 `assigned_at`의 날짜가 잘못 표기되는 현상이 있습니다.
JS Date는 날짜만 있는 스트링으로 생성될 때 UTC의 00:00으로 추측해서, `toLocaleString`을 사용하면 현재 시간대로 변환된 날짜를 반환합니다.

시간대가 UTC-4인 경우:
```js
const date = new Date("2024-10-04") 
console.log(date.toUTCString()) //  Fri, 04 Oct 2024 00:00:00 GMT
console.log(date.toLocaleDateString()) // 10/3/2024
```

10월 4일로 표기되어야 맞지만, 하루 전 날짜인 10월 3일로 표시되는 것을 확인할 수 있습니다.
이 문제를 해결하기 위해서는 luxon의 DateTime을 사용하는 것을 제안합니다.

luxon의 DateTime은 생성할 때부터 시간대를 지정할 수 있습니다.

```js
const date = DateTime.fromISO("2024-10-04", { zone: "America/New_York" })
console.log(date.toISODate()) // 2024-10-04
```

따라서 `taskDate.jsx` 파일의 모든 Date 객체를 전부 luxon의 DateTime 객체로 바꾸는 것을 추천합니다!
또한, 앞으로도 날짜만 있는 ISO 8601 형식의 스트링을 `DateTime` 객체로 파싱해야 한다면, `fromISO` 함수에 `zone`을 꼭 명시할 것을 권장합니다.

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskDate.jsx
>              })
`setting.time_as_24_hour` 값을 `hour12`로 전달한다면 코드 길이를 굉장히 간소화할 수 있을 것 같습니다.

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/project/due/TimeDetail.jsx
> +    const due_datetime = DateTime.fromJSDate(new Date(due)).setZone(tz)
날짜만 있는 ISO 8601 포맷의 스트링이 파싱되기 때문에,
```js
const due_datetime = DateTime.fromISO(due, { zone: tz })
```
로 작성할 것을 권장합니다. 이유는 `taskDate.jsx` 파일에 남긴 코멘트를 확인해주세요!

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskCalculation.jsx
> +        taskDue = DateTime.fromJSDate(new Date(task.due_date)).setZone(tz)
날짜만 있는 스트링이기 때문에
```js
taskDue = DateTime.fromISO(task.due_date, { zone: tz })
```
로 작성할 것을 권장합니다. 이유는 `taskDate.jsx` 파일에 남긴 코멘트를 확인해주세요!

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskCalculation.jsx
> +        taskDue = DateTime.fromJSDate(new Date(task.due_datetime)).setZone(tz)
`DateTime.fromISO`를 사용할 것을 권장합니다.

2024-10-04 05:29 UTC, JedBeom commented on frontend/src/components/project/taskDetails/Assigned.jsx
> +            const date = today.plus({ days: set })
한 달 뒤로 설정했을 때, 한 달 뒤가 아닌 30일 뒤로 설정되는 것으로 보입니다.
set을 Number 대신 `{ days: 1}`, `{ months: 1 }` 같은 객체로 넘기면 **진짜** 한 달 뒤로 설정할 수 있을 것 같습니다.

2024-10-07 14:43 UTC, minyoy commented on frontend/src/components/tasks/utils/taskDate.jsx
>              })
`hour12: setting.time_as_24_hour`를 말하시는 걸까요..?

2024-10-07 14:58 UTC, JedBeom commented on frontend/src/components/tasks/utils/taskDate.jsx
>              })
`hour12: !setting.time_as_24_hour`입니다!

2024-10-07 15:22 UTC, minyoy commented
코멘트 감사합니다! 달아주신 것들 모두 수정했습니다 :)
+ 추가로 리마인더 생성오류도 같이 수정했습니다~

2024-10-07 21:59 UTC, JedBeom requested changes
수정 감사합니다! 이제 시간대 관련 문제는 해결된 것 같습니다.
이제 사소한 문제만 남았습니다. 두 개 코멘트만 더 확인해주시면 감사하겠습니다!

2024-10-07 21:59 UTC, JedBeom commented on backend/notifications/views.py
> +            converted_due_datetime = datetime.combine(date=converted_due_date, time=nine_oclock_time)
`task.due_date`는 이미 `date` 객체입니다. `datetime.fromisoformat`으로 `datetime` 객체로 바꾸지 않아도 combine이 가능합니다.

2024-10-07 21:59 UTC, JedBeom commented on backend/notifications/views.py
> +            converted_due_datetime = datetime.fromisoformat(str(task.due_datetime))
`task.due_datetime`은 이미 `datetime` 객체입니다.

2024-10-08 01:01 UTC, minyoy commented
수정 완료했습니다!👍👍😊😊

2024-10-08 05:07 UTC, JedBeom approved these changes
LGTM ☺️

2024-10-08 05:07 UTC, merged