TaskDetail과 TaskCreate 컴포넌트 수정 + #176
GooseMoment/Peak pull request #281
Opened 2024-10-09 05:45 UTC by minyoy

- 여러분의 코멘트에 따라 `TaskDetail`에 **수정 버튼**을 추가하였습니다. 이제 설정 버튼을 누르면 바로 `backend`로 요청이 가는 것이 아니라 프론트의 useState가 수정되며, 수정 버튼을 클릭해야 `backend`로 요청이 갑니다.
- `TaskDetail`과 `TaskCreate` 두 컴포넌트에서 공통되는 부분을 `TaskCommonDetail` 파일로 분리하였습니다.

- #176 이슈를 해결했습니다.
_이제 `Reminder`는 `object` 형태로 `newTask`(useState 값)에 저장되는 것이 아니라, `Array`로 `newTask`에 저장됩니다.
`backend`로 요청을 보낼 때는 배열의 delta를 오브젝트로 변환해 전송합니다. 
수정 또는 생성 버튼 클릭 시, `patchTask()` 또는 `postTask()` 함수 실행 후에 `postReminder()` 함수가 실행됩니다.
`postReminder()` 함수 실행 시, 기존에 있던 `reminders`는 모두 삭제되며 `reminders`를 새로 생성합니다._

2024-10-09 17:41 UTC, JedBeom requested changes
수정 감사합니다. 리마인더와 `TaskCreateSimple` 관련해서 몇 가지 이슈가 있습니다. 확인해주시면 감사합니다.

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +        }
만약 리마인더가 설정된 상태에서 모두 설정 해제하면, 리마인더가 삭제되지 않습니다.

https://github.com/user-attachments/assets/2899281e-2a04-4b56-a474-a99b43dfa07d

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +        newTask && (
제안:
```jsx
if (!newTask) {
    return null
}

return (
    <TaskDetailBox ...
```

이런 형식은 어떨까요?

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +        },
`isCreating = false`일 때의 에러 메시지도 필요하지 않을까요?

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +            newTask.reminders.forEach((delta) => {
```js
newTask.reminders?.forEach((delta) => {
```

로 작성하면 if문을 간소화할 수 있습니다.

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +`
`ButtonGroup`을 사용하면 스타일을 하지 않고도 버튼 오른쪽 정렬이 가능합니다.

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskDetail.jsx
>  const TaskDetailBox = styled.div`
`TaskCommonDetail`의 `TaskDetailBox`를 사용하는 건 어떨까요?

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +    const onEnter = (e) => {
`mutation.isPending`이 참일 때를 검사하는 것도 좋을 것 같습니다.

2024-10-09 17:41 UTC, JedBeom commented on backend/notifications/views.py
> +
개발 환경에서는 서버로 요청을 보내는 속도가 빨라서 체크가 어려웠을 수도 있는데, 이 코드 때문에 일반 속도 환경에서는 가장 마지막으로 보낸 리마인더 1개만 남게 됩니다.

5분, 15분, 30분 리마인더 생성 요청을 차례대로 보낼 경우:

1. 5분 요청: 기존 리마인더 삭제, 5분 생성
2. 15분 요청: 5분 리마인더 삭제하게 됨, 15분 생성
3. 30분 요청: 15분 리마인더 삭제하게 됨, 30분 생성

결국 30분 리마인더 한 개만 남게 됩니다.

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
`TaskCreate`와 `TaskDetail`을 `TaskEdit` 같은 이름으로 하나로 합치는 건 어떨까요?

2024-10-09 17:41 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +            })
질문: 작업을 삭제할 때 프로젝트와 서랍도 invalidate해야하나요?

2024-10-10 06:03 UTC, JedBeom commented
추가로, 작업이 수정될 때마다 리마인더를 삭제 및 재생성하는 방향으로 가신다면, 백엔드의 `TaskDetail` 뷰의 리마인더 관련 코드도 수정 또는 삭제 부탁드립니다.

2024-10-10 15:42 UTC, minyoy commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +            })
네!! Project goal view의 그래프에서 사용됩니다!

2024-10-11 17:27 UTC, JedBeom commented on frontend/src/components/project/taskDetails/TaskCommonDetail.jsx
> +            })
그럼 type이 goal일 때만 invalidate하는 건 어떨까요?

2024-10-15 13:25 UTC, minyoy commented
코멘트 감사합니다! 모두 수정했습니다!
오늘 컨디션이 안좋아서 너무 이상하게 구현했을까봐 약간 걱정이 되긴하지만..😢

2024-10-15 22:31 UTC, JedBeom requested changes
리마인더에 관한 수정 감사합니다.
몇 가지 요소만 더 확인해주시면 감사하겠습니다.

2024-10-15 22:31 UTC, JedBeom commented on backend/notifications/views.py
> +        return Response(status=status.HTTP_201_CREATED)
201 상태 코드를 사용할 때는 새로 생성된 리소스나 이에 대한 설명이 응답에 함께 첨부되어야 합니다. ([MDN](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201))
새 리마인더(들)를 같이 반환하거나, 그냥 `200`을 반환하는 게 좋습니다.

2024-10-15 22:31 UTC, JedBeom commented on backend/notifications/views.py
> +                task.reminders.all().delete()
이 부분을 조건문 위로 옮기고, 조건문 속 중복된 코드를 삭제해도 괜찮을 것 같습니다.

2024-10-15 22:31 UTC, JedBeom commented on backend/notifications/views.py
> +            delta_array = request.data["delta_array"]
제안: `array`보다 `deltas` 또는 `delta_list`가 의미를 더 잘 나타낼 것 같습니다.

2024-10-15 22:31 UTC, JedBeom commented on backend/notifications/views.py
> +            task = Task.objects.get(id=task_id)
<img width="1202" alt="Screenshot 2024-10-15 at 18 14 10" src="https://github.com/user-attachments/assets/236f2941-f7b3-4214-bec9-7816a5d794f2">
`task_id`가 올바르지 않을 경우 `404`가 반환되어야 하는데, 현재는 처리되지 않은 예외 때문에 `500`이 반환됩니다.

2024-10-15 22:31 UTC, JedBeom commented on backend/notifications/views.py
> +        return Response(status=status.HTTP_201_CREATED)
`task`와 `delta_array`가 주어지지 않으면 아무 일도 일어나지 않음에도 `201`이 반환됩니다.

2024-10-31 15:53 UTC, minyoy commented
코멘트 달아주신 것들 다 수정했습니다 !

2024-10-31 18:19 UTC, JedBeom requested changes
수정 감사합니다. 마지막으로 두 가지만 더 확인해주세요! 감사합니다.

2024-10-31 18:19 UTC, JedBeom commented on backend/notifications/views.py
>                      nine_oclock_time = time(hour=9, minute=0, second=0, tzinfo=ZoneInfo(str(tz)))
#273 PR에서 `TimezoneMixin.get_tz()`에서 `ZoneInfo`를 반환하도록 변경되었습니다. 이제 `tz`를 그대로 사용해주세요.

2024-10-31 18:19 UTC, JedBeom commented on backend/notifications/views.py
> +from django.shortcuts import get_object_or_404
아직 파이썬에서 임포트 순서를 약속하진 않았지만, Peak 내부 패키지와 다른 패키지의 임포트 경로가 섞이지 않게 수정해주시면 감사하겠습니다!

2024-11-01 03:57 UTC, JedBeom commented
@minyoy 머지 컨플릭트 해결해주시면 리뷰 진행하겠습니다!

2024-11-01 04:06 UTC, minyoy commented
해결했습니다~

2024-11-01 08:09 UTC, JedBeom approved these changes
Awesome!

2024-11-01 08:09 UTC, merged