Social 모바일화 및 구조적 개선
GooseMoment/Peak pull request #289
Opened 2024-10-14 16:48 UTC by andless2004

우선 커밋이 극단적으로 많이 커져 리뷰에 어려움을 드린 점 진심으로 사과드립니다...

# 모바일화
> ## FollowingPage
> - Following Page 모바일 버전을 추가했습니다. 
> - 기존과 다르게 Quote, LogDetails 등 자세한 내용은 해당 사용자의 preview 박스를 클릭하면 열립니다.
<image img="https://github.com/user-attachments/assets/ccb671c6-589a-4b5a-97a7-edeb206dccbd" width="60%">
<image img="https://github.com/user-attachments/assets/379acbf2-8ed0-48ba-a8e9-219a4152107b" width="60%">

> ## ExplorePage

2024-10-15 22:00 UTC, JedBeom requested changes
드디어 소셜에도 모바일화의 바람이 불다니 정말 기쁩니다. 변경사항 정말 잘 읽어보고 확인하였습니다.
평소와 같이 몇 가지 수정해야할 사항을 남겨두었습니다.
+ 제 생각에는 프론트엔드 디자인(데스크탑과 모바일 둘다)에 대해서 좀 더 논의가 필요할 것 같습니다. 일단 간단하게 소셜 팔로잉 페이지의 모바일 화면을 피그마에 추가해두었습니다. 한 번 확인해보시고 고려 부탁드립니다!

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/logDetails/LogDetails.jsx
> +                                    color={task.project_color}
`getProjectColor`를 이용해야 합니다.

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/pages/SocialFollowingPage.jsx
<img width="1004" alt="Screenshot 2024-10-15 at 17 27 26" src="https://github.com/user-attachments/assets/8cb3fe00-9eaf-41b7-9a52-17de07d0c382">
<img width="732" alt="Screenshot 2024-10-15 at 17 31 09" src="https://github.com/user-attachments/assets/c3eed0f9-d136-4a0f-9717-bd4b760e244e">

어중간한 화면 크기에서 오른쪽 부분이 가려지는 경우가 있습니다.

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/pages/SocialFollowingPage.jsx
모바일에서 `LogPreviewBox`를 눌렀을 때 그 자리에서 열리는 것보다, 새 페이지로 이동하는 게 좋을 것 같습니다.

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/pages/SocialFollowingPage.jsx
팔로잉 페이지에 대한 새로운 디자인을 제안해봅니다. 피그마의 소셜 섹션의 오른쪽 부분에 만들어 두었습니다! 
<img width="734" alt="Screenshot 2024-10-15 at 17 30 29" src="https://github.com/user-attachments/assets/bc7d6773-d4ab-44f0-869f-57d720e343c6">

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/logsPreview/LogPreviewBox.jsx
> +                        <RecentTask data-accept="true">
`data-accept="true"` 속성은 어떤 이유로 추가되었나요?

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
>      if (!isOpen || !emojis) return null
<img width="847" alt="Screenshot 2024-10-15 at 17 43 50" src="https://github.com/user-attachments/assets/790ebbbc-a186-4796-8197-01d05eb75d9a">
`EmojiModal`을 열 때 위와 같은 오류가 발생합니다. 보통 이 오류는 컴포넌트를 렌더링할 때 `useState`와 같은 훅의 호출 횟수가 달라질 때 발생하는 오류입니다. 이 if문을 `useXXXX` 훅들 아래로 내리시거나, 삭제해야합니다.

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
화면 너비가 작을 때 에모지끼리 겹치는 문제가 발생합니다. 정사각형이 아닌 에모지가 추가될 때 작은 화면 너비가 아니더라도 에모지가 겹칠 가능성이 있습니다.
<img width="306" alt="Screenshot 2024-10-15 at 17 45 21" src="https://github.com/user-attachments/assets/aa0bed6f-c581-44d3-98a5-3b2fbc422b71">

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/logDetails/LogDetails.jsx
> +                                    <DrawerName $color={task.project_color}>
`getProjectColor`를 이용해야 합니다.

2024-10-15 22:00 UTC, JedBeom commented on frontend/src/components/social/logDetails/LogDetails.jsx
> +    font-size: larger;
제안: 글씨가 크지 않아도 괜찮을 것 같습니다.

2024-10-15 22:00 UTC, JedBeom commented on backend/social/views.py
> +        day_range = (day_min, day_max)
이 뷰에 투데이 뷰와 같이 `TimezoneMixin`을 사용하는 건 어떨까요?

2024-10-28 06:05 UTC, andless2004 commented on frontend/public/locales/en/translation.json
> +        "log_preview_completed": "completed!",
"{task} completed" 표현에서 어느 부분이 어색한 걸까요..? 아시다시피 영어가 많이 취약해서.... 번거로우시겠지만 예시 문장을 주실 수 있으시다면 감사하겠습니다ㅠㅜ

2024-10-28 06:08 UTC, andless2004 commented on backend/social/views.py
> +        day_range = (day_min, day_max)
해당 부분은 인지하고 있습니다! 현재 Social API들이 모두 이런 방식을 사용하고 있어 dailylog와 그 관련 view들을 고치는 PR에서 함께 수정하겠습니다!! 확인해 주셔서 감사합니다 :)

2024-10-28 06:25 UTC, andless2004 commented on frontend/public/locales/en/translation.json
> +            "no_result" : "Can't find the user you're looking for 😢",
```"No users matched your search"````, ```"We couldn't find any users matching your search."``` 요런 건 어떤가요?? 조금 더 친근한...?

2024-10-28 06:53 UTC, andless2004 commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
>      if (!isOpen || !emojis) return null
앗 감사합니다! 사실 지워도 됐던 거 같은데 우선은 옮겨놓고 검토하면서 다시 보겠습니다..! 감사합니다~

2024-10-28 07:03 UTC, andless2004 commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
혹시 화면 너비가 어느 정도일까요??

2024-10-28 12:39 UTC, andless2004 commented on frontend/src/components/social/logDetails/LogDetails.jsx
> +    font-size: larger;
좋습니당

2024-10-28 12:45 UTC, andless2004 commented on frontend/src/components/social/logsPreview/LogPreviewBox.jsx
> +                        <RecentTask data-accept="true">
지금 모바일 디자인에선 preview에서 detail을 여는 구조를 가지고 있습니다. 이때 detail에서 발생하는 이벤트가 preview box로 전달되어 닫히는 것을 방지하기 위해 추가했습니다.
다만 제안해주신 방향으로 디자인을 변경하며 필요없어질 것 같습니다.

2024-10-28 12:46 UTC, andless2004 commented on frontend/src/pages/SocialFollowingPage.jsx
좋은 의견 감사합니다!

2024-10-28 13:14 UTC, andless2004 commented on frontend/src/pages/SocialFollowingPage.jsx
당장은 Tablet일 때도 Mobile랑 같은 배치로 해결하면 되긴 하는데.. 디자인 변경 탓에 해결책은 아닐 것 같네요......
괜찮다면 디자인 변경과 함께 수정해도 될까요?
추가로 Tablet 너비 경계를 1200정도로 좀 더 넓게 잡는 건 어떨까요??

2024-10-28 17:33 UTC, JedBeom commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
너비 270px에서 확인할 수 있습니다. 

이 정도로 좁은 기기가 흔치는 않겠지만, 추후 상황을 위해 수정하는 게 좋을 것 같다는 말씀 드립니다!

2024-10-28 17:37 UTC, JedBeom commented on frontend/public/locales/en/translation.json
> +            "no_result" : "Can't find the user you're looking for 😢",
코멘트에 오타가 나 있었네요. 의도한 말은 `"Your search did not match any users."`였습니다.
UX 메시지는 짧게 유지할수록 좋다고 생각합니다. `"Your search did not match any users."`나 `"No users matched your search."` 중에 택 1 하시면 좋을 것 같습니다.

2024-10-30 06:17 UTC, andless2004 commented on frontend/public/locales/en/translation.json
> +            "no_result" : "Can't find the user you're looking for 😢",
감사합니다!

2024-10-30 16:20 UTC, JedBeom commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
270px을 어떻게 봤냐는 질문인가요?
개발자도구 키고 너비 조정했습니다.

2024-10-30 16:33 UTC, JedBeom requested changes

2024-10-30 16:33 UTC, JedBeom commented on frontend/src/api/social.api.js
> -export const getDailyLogTasks = async (drawerID, day, page) => {
`getDailyLogTasks`가 사라지면서 `IntroPage` 접속 시 `DrawerBundle` 관련 에러가 발생합니다.

```
SyntaxError: The requested module '/src/api/social.api.js?t=1730305580929' does not provide an export named 'getDailyLogTasks' (at DrawerBundle.jsx:10:10)
```

`main`과의 머지 후에, `DrawerBundle.jsx` 파일 삭제를 부탁드립니다.

2024-10-31 03:49 UTC, andless2004 commented on frontend/src/components/social/interaction/reaction/EmojiModal.jsx
앗 다른 브랜치에서 잘못 확인했습니다;; 수정했습니다! 감사합니다~

2024-10-31 03:56 UTC, andless2004 commented on frontend/src/api/social.api.js
> -export const getDailyLogTasks = async (drawerID, day, page) => {
네 감사합니다!

2024-10-31 05:09 UTC, JedBeom requested changes
머지 컨플릭트 해결하면서 문제가 있었던 듯합니다. 해결 부탁드리고, 메인과의 머지 한 번 더 부탁드립니다.

2024-10-31 05:09 UTC, JedBeom commented on frontend/src/pages/SocialExplorePage.jsx
> +        queryFn: (page) => getExploreFound(searchQuery, page.pageParam),
`queryFn:`이 중복되어 있습니다.

2024-10-31 05:09 UTC, JedBeom commented on frontend/src/pages/SocialExplorePage.jsx
>          getNextPageParam: (lastPage) => getCursorFromURL(lastPage.next),
`getCursorFromURL`이 정의되지 않았습니다. 지우신 `@utils/pagination'의 임포트를 다시 넣어주세요.

2024-10-31 06:52 UTC, andless2004 commented on frontend/src/pages/SocialExplorePage.jsx
>          getNextPageParam: (lastPage) => getCursorFromURL(lastPage.next),
악.. 감사합니다

2024-10-31 17:46 UTC, JedBeom approved these changes
Great!

2024-10-31 17:46 UTC, merged