Task: Hover 시 삭제 버튼 추가 및 모바일 삭제버튼 추가
GooseMoment/Peak pull request #297
Opened 2024-11-10 13:24 UTC by minyoy

### 1. Task: Hover 시 삭제 버튼 추가
<img width="847" alt="스크린샷 2024-11-10 오후 10 17 16" src="https://github.com/user-attachments/assets/293bf311-d466-4d7e-80cf-6df9fc078ec5">

이제 `Task`에 `hover`만 해도 `Task` 삭제버튼이 생기며, 이 버튼을 누를 시 `Task`가 삭제됩니다.
**'설정: 작업 삭제 시 경고'에 따라 경고창을 띄우거나 띄우지 않습니다.**

### 2. 모바일 삭제버튼 추가
<img width="284" alt="스크린샷 2024-11-10 오후 10 19 21" src="https://github.com/user-attachments/assets/f965710c-ba42-4abd-8fda-94c0ddbcfb66">

모바일에서도 `Task`를 삭제할 수 있게 수정하였습니다.
`Task` 수정에서 `Task`를 삭제할 수 있으며 설정에 상관없이 경고창을 띄우지 않고 바로 삭제합니다.

*위와 같이 '설정: 작업 삭제 시 경고'에 따라 경고창을 띄우거나 띄우지 않을 예정이나, 현재 모바일 바텀시트에서 경고창의 버튼이 제대로 작동하지 않아 **임시로 설정에 상관없이 경고창을 띄우지 않고 삭제하도록 하였습니다**.

2024-12-14 18:14 UTC, JedBeom requested changes
모바일 화면 작업에 힘 써주셔서 감사합니다. 몇 가지 수정 사항과 제안사항을 남겼습니다. 감사합니다.

2024-12-14 18:14 UTC, JedBeom commented on frontend/src/components/tasks/DrawerTask.jsx
> +            toast.error(t("delete_error", { task_name: task.name }))
'toast' is not defined.

2024-12-14 18:14 UTC, JedBeom commented on frontend/src/components/tasks/DrawerTask.jsx
> +    const deleteMutation = useMutation({
`TaskCommonDetail:79L` 부분과 동일한 코드 같습니다. 혹시 공통 부분으로 분리할 순 없을까요?

2024-12-14 18:14 UTC, JedBeom commented on frontend/src/components/project/taskDetails/mobile/TaskCommonDetailMobile.jsx
> +    // #TODO: AlertOpen 되게 하기
`BottomSheet` 컴포넌트에 `blocking={false}`를 전달하면 모달 버튼이 눌립니다. [참고](https://github.com/stipsan/react-spring-bottom-sheet/blob/main/pages/fixtures/aside.tsx#L41-L53)
모달이 띄워졌을 때만 `blocking` 인자를 `false`로 전달하면 될 것 같습니다.

2024-12-26 07:47 UTC, minyoy commented
리뷰 감사합니다~ 모두 수정하였습니다!

2024-12-29 00:52 UTC, JedBeom requested changes

2024-12-29 00:52 UTC, JedBeom commented on frontend/src/components/common/ModalBottomSheet.jsx
> +            blocking={false}
`Confirmation` 모달이 띄워졌을 때만 `blocking={false}`를 주는 게 어떨까요?

2025-02-03 21:23 UTC, JedBeom commented
<img width="376" alt="Screenshot 2025-02-03 at 16 21 50" src="https://github.com/user-attachments/assets/b91c940b-ffb6-40f0-a532-c7a1c68a1cbc" />
Confirmation 모달이 없을 때(위 사진 상태)는 `blocking={true}`를 주고, 

<img width="376" alt="Screenshot 2025-02-03 at 16 21 57" src="https://github.com/user-attachments/assets/8ffd5ece-78fe-4248-84a7-9de5615ec6f6" />
Confirmation 모달이 있을 때 (위 사진)만 `blocking={false}`를 주는 건 어떨까요?

2025-02-05 21:52 UTC, minyoy commented
모두 해결했습니다!

2025-02-06 01:22 UTC, JedBeom approved these changes
LGTM ☺️

2025-02-06 01:22 UTC, merged